name: Password Analyzer CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety pytest pytest-cov
    
    # Security scanning with Bandit
    - name: Run Bandit security scan
      run: bandit -r ./src -f json -o bandit-results.json
    
    # Dependency security check
    - name: Check dependencies for security issues
      run: safety check
    
    # Run tests with coverage
    - name: Run tests with coverage
      run: pytest --cov=src tests/ --cov-report=xml
    
    # Upload coverage report
    ```yaml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        retry_max_attempts: 3
        retry_delay_seconds: 600  # 10 minutes between retries
```

  build-and-test:
    needs: security-checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run tests
      run: pytest tests/